-- MySQL Script generated by MySQL Workbench
-- Sun Oct  3 19:16:15 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ORGANIZEI
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ORGANIZEI` ;

-- -----------------------------------------------------
-- Schema ORGANIZEI
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ORGANIZEI` ;
USE `ORGANIZEI` ;

-- -----------------------------------------------------
-- Table `ORGANIZEI`.`USUARIO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ORGANIZEI`.`USUARIO` ;

CREATE TABLE IF NOT EXISTS `ORGANIZEI`.`USUARIO` (
  `CPF` CHAR(11) NOT NULL,
  `Nome` VARCHAR(200) NOT NULL,
  `Senha` VARCHAR(45) NOT NULL,
  `E-mail` VARCHAR(45) NOT NULL,
  `DataNasc` DATE NOT NULL,
  PRIMARY KEY (`CPF`),
  UNIQUE INDEX `E-mail_UNIQUE` (`E-mail` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ORGANIZEI`.`NOTA_FISCAL`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ORGANIZEI`.`NOTA_FISCAL` ;

CREATE TABLE IF NOT EXISTS `ORGANIZEI`.`NOTA_FISCAL` (
  `Chave` CHAR(44) NOT NULL,
  `DataEmissao` DATE NOT NULL,
  `Valor` DECIMAL(6,2) NOT NULL,
  `EmpresaCNPJ` CHAR(14) NOT NULL,
  `EmpresaNome` VARCHAR(200) NOT NULL,
  `EmpresaAtividade` VARCHAR(200) NULL,
  `USUARIO_CPF` CHAR(11) NOT NULL,
  PRIMARY KEY (`Chave`, `USUARIO_CPF`),
  INDEX `fk_NOTA_FISCAL_USUARIO_idx` (`USUARIO_CPF` ASC) VISIBLE,
  CONSTRAINT `fk_NOTA_FISCAL_USUARIO`
    FOREIGN KEY (`USUARIO_CPF`)
    REFERENCES `ORGANIZEI`.`USUARIO` (`CPF`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
